---
title: ""
---

Hello, welcome to my personal webpage. This site showcases my projects, tools, and applied economic work particularly in pesticide regulations.

I am a PhD Economist at the U.S. Environmental Protection Agency (EPA). There, I work at the Office of Pesticide Programs evaluating impacts to agriculture that could result from various pesticide-policy actions from the Agency. 

I'm interested in environmental and resource economics, broadly, as well as econometrics in quasi-experimental settings. I have extensive experience analyzing economic/policy questions related to agricultural pollution starting with my job market paper. The paper compares the economic trade offs between two approaches to regulatoe non-point source pollution: using group-based market incentives vs. technological standards (command-and-control). 

In my tenure at EPA's Office of Pesticide Programs, I have gained valuable experience in economic analyses used to support regulatory decision making including partial budget analysis, impacts of non-tariff trade restrictions, cost-benefit analysis, capital budgeting, and econometric evaluations of epidemiological studies. I have also had the privilege to undertake a broad array of data projects including geospatial analysis and database management, automated workflows using R Shiny, and creating and managing big databases utilizing DuckDB and parquet file formatting. 
